### ISSUE TITLE
Confirmation window does not appear on top of other windows

### ISSUE THREAD

**Issue by sawdust64** [broken-e/DragDropConfirm#20]
I like what this little tool does, but most of the time the confirmation pops up behind other open windows. This makes it a few more clicks to use and select the window and click ok. it also makes it confusing when you first start using this tool and are not thinking about it and wonder why that file you just dragged isn't moving.

Is there a way to always make the confirmation window pop up on top of all other windows?

Thanks

**Comment by bduffek** [comment]
Which version are you using?  This should have been fixed a long time ago.  Where did you download it from?

**Comment by sawdust64** [comment]
http://broken-e.com/dragdropconfirm
this is where i got it from. about 6 months ago maybe. I kinda assumed it was not updated that much, but ill try the newest one from here and see if it helps.

Thanks

**Comment by bduffek** [comment]
Yeah that one is very out of date unfortunately.  The creator actually did show up here about a month ago, but I didn't think to ask him about his site.  I'm not an expert on this stuff but know enough to tweak it, so he gave me contributor controls.

**Comment by sawdust64** [comment]
Just downloaded the newest one from Github, still getting the same issue. It appears that if the window i am copying FROM is the active window, the message will pop on top, but if any other window is selected and the active window, then then the message pops below other windows.

system specs if relevant or helpful:
![image](https://user-images.githubusercontent.com/25359175/45449645-bb1d8a80-b6a3-11e8-91db-72054c318fe4.png)

**Comment by bduffek** [comment]
To be clear, did you uninstall the previous one first?  If you right click one of the two DLLs and check the properties what version does it say?

**Comment by bduffek** [comment]
Oh no problem, and thank you for bringing it up that the old one is still referenced on his site.
